### ISSUE TITLE
ANTLR4 version mismatch

### ISSUE THREAD

**Issue by blennster** [Venom1991/refind-btrfs#29]
Hi,

The [python-antlr4](https://archlinux.org/packages/community/any/python-antlr4/) package in the arch repos has recently been updated (2022-04-12) and causes the following error when running `refind-btrfs`:

> Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.10/site-packages/refind_btrfs/__init__.py", line 36, in <module>
    from refind_btrfs.utility.injector_modules import CLIModule, WatchdogModule
  File "/usr/lib/python3.10/site-packages/refind_btrfs/utility/injector_modules.py", line 30, in <module>
    from refind_btrfs.boot.file_refind_config_provider import FileRefindConfigProvider
  File "/usr/lib/python3.10/site-packages/refind_btrfs/boot/file_refind_config_provider.py", line 51, in <module>
    from .antlr4 import RefindConfigLexer, RefindConfigParser
  File "/usr/lib/python3.10/site-packages/refind_btrfs/boot/antlr4/__init__.py", line 24, in <module>
    from .RefindConfigLexer import RefindConfigLexer
  File "/usr/lib/python3.10/site-packages/refind_btrfs/boot/antlr4/RefindConfigLexer.py", line 433, in <module>
    class RefindConfigLexer(Lexer):
  File "/usr/lib/python3.10/site-packages/refind_btrfs/boot/antlr4/RefindConfigLexer.py", line 435, in RefindConfigLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/usr/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/usr/lib/python3.10/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version " + str(version) + " (expected " + str(SERIALIZED_VERSION) + ").")
Exception: Could not deserialize ATN with version  (expected 4).

Let me know if there is anything I can do to help!

**Comment by Venom1991** [comment]
I have to update those packages on my machine, regenerate the ANTLR code and release a new version. I'll try to do it today.

**Comment by Venom1991** [comment]
It should be fine now, just update the package and try it again. Please close the issue if it doesn't break anymore.  
Sorry for the trouble.

**Comment by blennster** [comment]
Wow that was really quick!

Thank you very much, it is working on machine now.
