### ISSUE TITLE
Aur: Service crashes

### ISSUE THREAD

**Issue by UltraBlackLinux** [Venom1991/refind-btrfs#43]
Hey there,
I just noticed, that the refind btrfs service crashes for me, running it manually via `sudo refind-btrfs` works as expected.

<details><summary>Backtrace</summary> 

```python
ERROR (refind_btrfs/__init__.py/main): An unexpected error happened, exiting...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/refind_btrfs/__init__.py", line 79, in main
    runner = injector.get(BaseRunner)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 970, in create_object
    reraise(e, CallError(instance, init_function, (), additional_kwargs, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 970, in create_object
    reraise(e, CallError(instance, init_function, (), additional_kwargs, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1010, in call_with_injection
    reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1008, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/usr/lib/python3.10/site-packages/refind_btrfs/service/snapshot_event_handler.py", line 68, in __init__
    super().__init__(package_config_provider)
TypeError: FileSystemEventHandler.__init__() takes 1 positional argument but 2 were given
```
</details>
Why is it crashing? Can you fix it?

Thanks!

**Comment by Venom1991** [comment]
Hi there, the problem is related to this [issue](https://github.com/Venom1991/refind-btrfs/issues/42).  
Basically, the watchdog authors introduced a breaking [change](https://github.com/gorakhargosh/watchdog/pull/861/files#diff-f35276dfb6b5b4b38f390449d6f5731f9c9acac16e38b08c3fbea254ae32f47aL179) some time ago. The related Arch [package](https://archlinux.org/packages/community/any/python-watchdog/) was updated yesterday, it seems.

I'll see what I can do on a Windows machine because my Arch install is still FUBAR.

**Comment by Venom1991** [comment]
@UltraBlackLinux 

I've updated the [AUR](https://aur.archlinux.org/packages/refind-btrfs) package, please update it, see if it fixed the issue by restarting the service and finally close the issue if applicable.

**Comment by UltraBlackLinux** [comment]
> @UltraBlackLinux
> 
> I've pushed a new version of the [AUR](https://aur.archlinux.org/packages/refind-btrfs) package so please upgrade it locally, see if it fixed the issue by restarting the service and finally close this issue (if applicable).

Nope, sadly still not working

**Comment by Venom1991** [comment]
Please paste the traceback, it shouldn't be identical to the previous one.

**Comment by UltraBlackLinux** [comment]
<details><summary>New Backtrace</summary> 

```python
ERROR (refind_btrfs/__init__.py/main): An unexpected error happened, exiting...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/refind_btrfs/__init__.py", line 79, in main
    runner = injector.get(BaseRunner)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 970, in create_object
    reraise(e, CallError(instance, init_function, (), additional_kwargs, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 999, in call_with_injection
    dependencies = self.args_to_inject(
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1047, in args_to_inject
    instance: Any = self.get(interface)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 943, in get
    result = scope_instance.get(interface, binding.provider).get(self)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 970, in create_object
    reraise(e, CallError(instance, init_function, (), additional_kwargs, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 966, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1010, in call_with_injection
    reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 190, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.10/site-packages/injector/__init__.py", line 1008, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/usr/lib/python3.10/site-packages/refind_btrfs/service/snapshot_event_handler.py", line 68, in __init__
    super().__init__(package_config_provider)
TypeError: FileSystemEventHandler.__init__() takes 1 positional argument but 2 were given
```
</details>

I thought this was the same :shrug:

**Comment by Venom1991** [comment]
> New Backtrace
> 
> I thought this was the same 🤷
> 
> And yes, I am on 0.5.4-1 now

Try the latest release (0.5.5-1) and report back when possible, please.

**Comment by UltraBlackLinux** [comment]
> > New Backtrace
> > I thought this was the same shrug
> > And yes, I am on 0.5.4-1 now
> 
> Try the latest release (0.5.5-1) and report back when possible, please.

Has now turned into
```python
ERROR (refind_btrfs.service.snapshot_observer/snapshot_observer.py/run): An unexpected error happened, exiting...
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/refind_btrfs/service/snapshot_observer.py", line 45, in run
         self.dispatch_events(self.event_queue)
         TypeError: BaseObserver.dispatch_events() missing 1 required positional argument: 'timeout'
```

**Comment by Venom1991** [comment]
I know what the problem is and I'll try to fix it in the morning.

**Comment by UltraBlackLinux** [comment]
> I know what the problem is and I'll try to fix it in the morning.

Great! Thank you!

> You did update the python-watchdog package?

`[2022-11-03T21:20:50+0100] [ALPM] upgraded python-watchdog (2.1.3-1 -> 2.1.4-1)`

Pacman log says yes

**Comment by Venom1991** [comment]
@UltraBlackLinux 

Check the new 0.5.6-1 release, please. I've added a kinda hacky solution but it should be fine, I hope.

**Comment by UltraBlackLinux** [comment]
> @UltraBlackLinux
> 
> Check the new 0.5.6-1 release, please. I've added a kinda hacky solution but it should be fine, I hope.

Seems to be working! Thank you!
