### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ThoriumTextile** [Venom1991/refind-btrfs#46]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/lib/python3.11/site-packages/refind_btrfs/__init__.py", line 36, in <module>
    from refind_btrfs.utility.injector_modules import CLIModule, WatchdogModule
  File "/usr/lib/python3.11/site-packages/refind_btrfs/utility/injector_modules.py", line 27, in <module>
    from transitions.core import State
ModuleNotFoundError: No module named 'transitions'
```
Happens when launched with sudo too.

**Comment by Venom1991** [comment]
@ThoriumTextile 

Do you have [this](https://aur.archlinux.org/packages/python-transitions) package installed? Are you using the [AUR](https://aur.archlinux.org/packages/refind-btrfs) provided package or did you install refind-btrfs from PyPI?

**Comment by ThoriumTextile** [comment]
> @ThoriumTextile
> 
> Do you have [this](https://aur.archlinux.org/packages/python-transitions) package installed? Are you using the [AUR](https://aur.archlinux.org/packages/refind-btrfs) provided package or did you install `refind-btrfs` from PyPI? Perhaps you need to rebuild Python packages which were installed from the AUR. See the pinned [comment](https://aur.archlinux.org/packages/refind-btrfs#comment-912673).

Turns out I had a broken version of said package. Now it runs but says it can't find the root partition:
```
Found the ESP mounted at '/efi' on '/dev/sda1'.
ERROR (refind_btrfs.state_management.conditions/conditions.py/check_filtered_block_devices): Could not find the root partition!
```

**Comment by Venom1991** [comment]
Please provide the output of:

`findmnt --json --mtab --real --nofsroot --output PARTUUID,PARTLABEL,UUID,SOURCE,FSTYPE,LABEL,TARGET,OPTIONS`

**Comment by ThoriumTextile** [comment]
> Please provide the output of:
> 
> `findmnt --json --mtab --real --nofsroot --output PARTUUID,PARTLABEL,UUID,SOURCE,FSTYPE,LABEL,TARGET,OPTIONS`

[findmnt.log](https://github.com/Venom1991/refind-btrfs/files/12709190/findmnt.log)

**Comment by Venom1991** [comment]
Something is going on with the "source" property of the root partition:

```
{
   "partuuid": "a6aaf844-791a-204c-ae01-ee53f24906cc",
   "partlabel": "CachyOS",
   "uuid": "490b080e-71f5-407a-bf88-bf954ff3ab31",
   "source": "/dev/disk/by-uuid/490b080e-71f5-407a-bf88-bf954ff3ab31",
   "fstype": "btrfs",
   "label": "CachyOS",
   "target": "/",
   "options": "rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,commit=120,subvolid=256,subvol=/@"
}
```

Please provide the output of:

```
lsblk --json --merge --paths --output NAME,TYPE,MAJ:MIN
lsblk /dev/sda --json --paths --tree --output PTUUID,PTTYPE,PARTUUID,PARTTYPE,PARTLABEL,UUID,NAME,FSTYPE,LABEL,MOUNTPOINT
```

Replace the "/dev/sda" part with the your root device's actual name.

The problem most likely has nothing to do with your setup because it obviously works (the OS itself, that is) but it does have to do with the fact that I never added support for `[persistent block device naming](https://wiki.archlinux.org/title/Persistent_block_device_naming#by-uuid)` and it seems to me that you've set up exactly that (or the OS installer, doesn't matter). It's on my to-do list but I just can't find the time to improve upon this tool.

**Comment by ThoriumTextile** [comment]
[lsblk1.log](https://github.com/Venom1991/refind-btrfs/files/12730910/lsblk1.log)
[lsblk2.log](https://github.com/Venom1991/refind-btrfs/files/12730911/lsblk2.log)


> Something is going on with the "source" property of the root partition:
> 
> ```
> {
>    "partuuid": "a6aaf844-791a-204c-ae01-ee53f24906cc",
>    "partlabel": "CachyOS",
>    "uuid": "490b080e-71f5-407a-bf88-bf954ff3ab31",
>    "source": "/dev/disk/by-uuid/490b080e-71f5-407a-bf88-bf954ff3ab31",
>    "fstype": "btrfs",
>    "label": "CachyOS",
>    "target": "/",
>    "options": "rw,noatime,compress=zstd:3,ssd,discard=async,space_cache,commit=120,subvolid=256,subvol=/@"
> }
> ```
> 
> I use it to match `findmnt`'s output with that of `lsblk`.
> 
> Please provide the output of:
> 
> ```
> lsblk --json --merge --paths --output NAME,TYPE,MAJ:MIN
> lsblk /dev/sda --json --paths --tree --output PTUUID,PTTYPE,PARTUUID,PARTTYPE,PARTLABEL,UUID,NAME,FSTYPE,LABEL,MOUNTPOINT
> ```
> 
> Replace the "/dev/sda" part with the your root device's actual name.
> 
> The problem most likely has nothing to do with your setup because it obviously works (the OS itself, that is) but it does have to do with the fact that I never added support for [persistent block device naming](https://wiki.archlinux.org/title/Persistent_block_device_naming) and it seems to me that you've set up exactly that (or the OS installer, doesn't matter), the [UUID](https://wiki.archlinux.org/title/Persistent_block_device_naming#by-uuid) method to be precise. It's on my to-do list but I just can't find the time to improve upon this tool.

**Comment by Venom1991** [comment]
Yeah, it's like I thought - the UUID block device naming method is causing problems. This is your root partition as reported by `lsblk`:

```
{
   "ptuuid": "343d7322-2e1a-44bd-b1f3-32bd70f2d27e",
   "pttype": "gpt",
   "partuuid": "a6aaf844-791a-204c-ae01-ee53f24906cc",
   "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
   "partlabel": "CachyOS",
   "uuid": "490b080e-71f5-407a-bf88-bf954ff3ab31",
   "name": "/dev/sda2",
   "fstype": "btrfs",
   "label": "CachyOS",
   "mountpoint": "/mnt/@rootfs"
}
```

Now, compare the "name" property with the "source" property in findmnt command's output. They're not exactly the same, unfortunately. Until I add support for persistent block device naming (or switch to using partition UUIDs, perhaps) you won't be able to run this tool. Of course, you could try and get rid of it but I don't exactly know how to do so, honestly, as I've never used it.

**Comment by CodingWithAnxiety** [comment]
I have multiple machines and, while pretty new to python, would love to honestly work on this and see what I can do. If I find a fix, and I make a merge request?

**Comment by Venom1991** [comment]
@CodingWithAnxiety 

Sure, I don't see why not. Try supporting the "[by-uuid](https://wiki.archlinux.org/title/Persistent_block_device_naming)" naming method first as it's the most common one (AFAIK).  
I don't have much free time to work on this tool, anymore.

**Comment by CodingWithAnxiety** [comment]
Right, so I've looked over the code, And... With VERY few comments, it's very difficult for me to comprehend how it's structured. Any idea where I should be starting?

**Comment by Venom1991** [comment]
Yep, no comments. It's also one of the things that should be added, perhaps even in [Sphinx](https://www.sphinx-doc.org/en/master/) syntax.

Anyway, I'd start [here](https://github.com/Venom1991/refind-btrfs/blob/8e0021a62d3d9446b8dcfdcdf0f97567dfdec232/src/refind_btrfs/system/findmnt_command.py#L115) as this is where `lsblk`'s output is matched with that received from `findmnt`.  
The whole codebase is typed so you should be able to navigate it with, for example, F12 in VS Code which is what I'm using to develop and debug this program. To debug, pressing F5 should be enough.

If you can't figure it out due to a lack of comments, that's also alright. I understand it's a bit convoluted but it's also pretty straightforward once you step through the whole process, i.e. from [here](https://github.com/Venom1991/refind-btrfs/blob/8e0021a62d3d9446b8dcfdcdf0f97567dfdec232/src/refind_btrfs/__init__.py#L80) onwards.
