### ISSUE TITLE
on starting refind-btrfs

### ISSUE THREAD

**Issue by ahmed-tasaly** [Venom1991/refind-btrfs#7]
Aloha there,
Recently on starting refind-btrfs this error appears
```
Initializing the block devices using lsblk.
Initializing the physical partition table for device '/dev/sda' using lsblk.
Initializing the live partition table for device '/dev/sda' using findmnt.
Initializing the physical partition table for device '/dev/sdb' using lsblk.
Initializing the live partition table for device '/dev/sdb' using findmnt.
Initializing the physical partition table for device '/dev/sdc' using lsblk.
Initializing the live partition table for device '/dev/sdc' using findmnt.
Initializing the physical partition table for device '/dev/zram0' using lsblk.
Initializing the live partition table for device '/dev/zram0' using findmnt.
Initializing the physical partition table for device '/dev/zram1' using lsblk.
Initializing the live partition table for device '/dev/zram1' using findmnt.
Initializing the physical partition table for device '/dev/zram2' using lsblk.
Initializing the live partition table for device '/dev/zram2' using findmnt.
Initializing the physical partition table for device '/dev/zram3' using lsblk.
Initializing the live partition table for device '/dev/zram3' using findmnt.
Initializing the physical partition table for device '/dev/zram4' using lsblk.
Initializing the live partition table for device '/dev/zram4' using findmnt.
Initializing the physical partition table for device '/dev/zram5' using lsblk.
Initializing the live partition table for device '/dev/zram5' using findmnt.
Initializing the physical partition table for device '/dev/zram6' using lsblk.
Initializing the live partition table for device '/dev/zram6' using findmnt.
Found the ESP mounted at '/boot/efi' on '/dev/sdb1'.
Found the root partition on '/dev/sdb3'.
Searching for snapshots of the 'ROOT/@' subvolume in the '/.snapshots' directory.
Found subvolume 'ROOT/@' mounted as the root partition.
Found 3 snapshots of the 'ROOT/@' subvolume.
Searching for the 'refind.conf' file on '/dev/sdb1'.
Analyzing the 'refind.conf' file.
ERROR (refind_btrfs.boot.file_refind_config_provider/file_refind_config_provider.py/_read_config_from): Error while parsing the 'refind.conf' file!
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/refind_btrfs/boot/file_refind_config_provider.py", line 253, in _read_config_from
    refind_context = parser.refind()
  File "/usr/lib/python3.9/site-packages/refind_btrfs/boot/antlr4/RefindConfigParser.py", line 185, in refind
    self.config_option()
  File "/usr/lib/python3.9/site-packages/refind_btrfs/boot/antlr4/RefindConfigParser.py", line 239, in config_option
    self.boot_stanza()
  File "/usr/lib/python3.9/site-packages/refind_btrfs/boot/antlr4/RefindConfigParser.py", line 312, in boot_stanza
    self._errHandler.sync(self)
  File "/usr/lib/python3.9/site-packages/antlr4/error/ErrorStrategy.py", line 223, in sync
    self.reportUnwantedToken(recognizer)
  File "/usr/lib/python3.9/site-packages/antlr4/error/ErrorStrategy.py", line 307, in reportUnwantedToken
    recognizer.notifyErrorListeners(msg, t, None)
  File "/usr/lib/python3.9/site-packages/antlr4/Parser.py", line 322, in notifyErrorListeners
    listener.syntaxError(self, offendingToken, line, column, msg, e)
  File "/usr/lib/python3.9/site-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
  File "/usr/lib/python3.9/site-packages/refind_btrfs/boot/refind_listeners.py", line 31, in syntaxError
    raise RefindSyntaxError(line, column, msg)
refind_btrfs.common.exceptions.RefindSyntaxError: RefindSyntaxError: line - 651, column - 65, message - 'extraneous input 'rw' expecting {MENU_ENTRY, 'volume', 'loader', 'initrd', 'icon', OS_TYPE, GRAPHICS, 'options', 'firmware_bootnum', 'disabled', '}'}'
ERROR (refind_btrfs.state_management.refind_btrfs_machine/refind_btrfs_machine.py/run): Could not load rEFInd configuration from file!
```

my menu entry : 
```
menuentry "EndeavourOS" {
     icon /EFI/refind/icons/os_endeavouros_alt.png
     volume endeavouros
     loader /ROOT/@/boot/vmlinuz-linux
     initrd /ROOT/@/boot/initramfs-linux.img
     options "root=PARTUUID=826a2285-25bc-3443-9fea-cda9f20b7b59 rw rootflags=subvol=ROOT/@ quiet loglevel=3 nowatchdog apparmor=1 security=apparmor radeon.si_support=0 amdgpu.si_support=1 add_efi_memmap initrd=ROOT\@\boot\intel-ucode.img bootsplash.bootfile=bootsplash-themes/manjaro-islamic-green/bootsplash"
     submenuentry "Boot using fallback initramfs" {
        initrd  /boot/initramfs-%v-fallback.img
     }
     submenuentry "Boot to terminal" {
         add_options "systemd.unit=multi-user.target"
     }
}
```

**Comment by Venom1991** [comment]
Hi there,

I'm gonna need your "refind.conf" (not just this stanza) so that I can see what exactly cannot be parsed.

**Comment by ahmed-tasaly** [comment]
> Hi there,
> 
> I'm gonna need your "refind.conf" (not just this stanza) so that I can see what exactly cannot be parsed.

### Oh I have found the problem after hours of searching -- but it was very funny 😂

menuentry "EndeavourOS - Manjaro-511" {
     icon /EFI/refind/icons/os_endeavouros.png
     volume endeavouros
     loader /ROOT/@/boot/vmlinuz-linux511
     initrd /ROOT/@/boot/initramfs-linux511.img
     options "root=PARTUUID=826a2285-25bc-3443-9fea-cda9f20b7b59 rw rootflags=subvol=ROOT/@ loglevel=3 nowatchdog apparmor=1 security=apparmor radeon.si_support=0 **amdgpu.cik
_support=1** amdgpu.si_support=1 add_efi_memmap initrd=ROOT\@\boot\intel-ucode.img bootsplash.bootfile=bootsplash-themes/manjaro-islamic-green/bootsplash"

**amdgpu.cik
_support=1**

should be 

**amdgpu.cik_support=1**

**Comment by ahmed-tasaly** [comment]
> Hi there,
> 
> I'm gonna need your "refind.conf" (not just this stanza) so that I can see what exactly cannot be parsed.

### **Thank you for your care and patience**

**Comment by Venom1991** [comment]
> 
> 
> > Hi there,
> > I'm gonna need your "refind.conf" (not just this stanza) so that I can see what exactly cannot be parsed.
> 
> ### Oh I have found the problem after hours of searching -- but it was very funny 😂
> 
> menuentry "EndeavourOS - Manjaro-511" {
> icon /EFI/refind/icons/os_endeavouros.png
> volume endeavouros
> loader /ROOT/@/boot/vmlinuz-linux511
> initrd /ROOT/@/boot/initramfs-linux511.img
> options "root=PARTUUID=826a2285-25bc-3443-9fea-cda9f20b7b59 rw rootflags=subvol=ROOT/@ loglevel=3 nowatchdog apparmor=1 security=apparmor radeon.si_support=0 **amdgpu.cik _support=1** amdgpu.si_support=1 add_efi_memmap initrd=ROOT@\boot\intel-ucode.img bootsplash.bootfile=bootsplash-themes/manjaro-islamic-green/bootsplash"
> 
> **amdgpu.cik _support=1**
> 
> should be
> 
> **amdgpu.cik_support=1**

So, an unexpected newline was the problem? Nice :laughing:
I'm glad that you figured it out. 👍🏼
